services:
  - type: web
    name: movie-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: SESSION_COOKIE_SAMESITE
        value: None
      - key: SESSION_COOKIE_SECURE
        value: "1"
